services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always

  database:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env.db
